#!/bin/sh

### BEGIN INIT INFO
# Provides:        torigemubot
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start Shiritori Game Telegram Bot daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/lib/torigemubot

. /lib/lsb/init-functions

DAEMON=/usr/local/lib/torigemubot/torigemubotsrv.sh
PIDFILE=/var/run/torigemubot.pid

test -x $DAEMON || exit 5

LOCKFILE=/run/lock/torigemubotdate

case $1 in
	start)
		log_daemon_msg "Starting Shiritori Game Bot server" "torigemubot"
		(
			flock -w 180 9
			start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE
		) 9>$LOCKFILE
		log_end_msg $?
  		;;
	stop)
		log_daemon_msg "Stopping Shiritori Game Bot server" "torigemubot"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --retry=TERM/30/KILL/5 --exec $DAEMON
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "Shiritori Game Bot server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
